### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by iYAMBERYPAMOUS** [H1B0B0/twitch-bot#1]
ADD an argument to use static proxy list with ip:port / user:pass:ip:port 
ADD an argument to use rotating proxy with ip:port along with an api to call http://exampe.com/api/change-ip/secret for each request. 

THIS PROJECT IS BY FAR THE BEST I'VE CAME ACROSS COMPARED TO OTHERS

**Comment by H1B0B0** [comment]
Hello okay i can make that 😀

**Comment by H1B0B0** [comment]
It's maked :) (only HTTP and ip:port format for this time). I gona upgrade the code when i have the time for that :).
